### ISSUE TITLE
use a central logging facility for all code

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#10]

**Comment by edaniszewski** [comment]
useful reference: http://docs.python.org/release/2.6/library/logging.html

**Comment by rohailaltaf** [comment]
master now logs to masterLog.txt and those changes are visible in the stat page

**Comment by acencini** [comment]
please verify this is the case for client and api as well.  assign to correct owner(s) and get these tied up by wednesday.

**Comment by rohailaltaf** [comment]
Logging functionality using python logging library complete. Closing.
