### ISSUE TITLE
API -- refactor socket logic in the API object

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#105]
I started to outline the continuous end-to-end test we need for Monday with @Kgespada , and now I ran a simple file create command, but in a for loop. 

The expected behavior: smoothly make new files/associated chunks for however many times the loop runs

The actual behavior: The first chunk gets created, and then a socket.error is thrown ( Errno 9 Bad file descriptor)

I did a quick look-over of the API and think that the main culprit for this is where you define your socket connections. Currently you declare the master socket connection in the object scope, so all methods of the object can use the master connection. Presumably, when I call create multiple times, it runs through the create method again, but because you closed the master connection in the first run through the create function (which is why the first file/chunk is still able to be created), subsequent requests have a bad connection. 

This should be solvable by removing the socket declaration from the object-wide scope, and instead have socket declarations at the object-method scope. This way when the specific method is called, it will create a new connection, and tear down that connection when it is done. This may even help with issue #96 ...

I'm not sure if I explained this well.. if not, come talk to me and I can help!

**Comment by ltraynor** [comment]
I totally get it. and actually im pretty sure I already had to add that to
append so multi-chunk would work.

On Thu, Nov 14, 2013 at 9:57 PM, Erick Daniszewski <notifications@github.com

**Comment by edaniszewski** [comment]
Okay cool!

Try to prioritize this work item, since it is crucial in getting the end-to-end test ready for Monday

**Comment by ltraynor** [comment]
BOOM. socket logic refactored. also #96 is fixed as well @edaniszewski verify

**Comment by edaniszewski** [comment]
Looks pretty good. Some things I noticed though:

around line 136, you didnt close the master connection
line 204 & 216, the self.s.close() can just be put outside of the conditional (around line 192) so you dont need to close it in two different locations
line 313, move the m.close() outside of the for loop  (to line 298 or thereabouts)
in the delete and undelete method, you dont close the connection to the master

now that you arent declaring a socket to the master at the object scope, you are going to need to create a socket connection within the fileList method

in the update oplog, you need to close the master also. If you do those things, it looks like it should be all good!

**Comment by ltraynor** [comment]
fixed

**Comment by edaniszewski** [comment]
verified!
