### ISSUE TITLE
listener.py - logging for the network is not in the right format

### ISSUE THREAD

**Issue by bgwalter** [BenningtonCS/GFS#107]
Currently it is: total sent / total received
It should subtract the previous number of bytes sent and received from the current numbers, and log the difference.

**Comment by acencini** [comment]
you are also welcome to boot this particular work to the presentation layer (aka Rohail) where his logic could do the delta computation.  you'd just need to be able to flag different counters as cumulative (like this) or absolute (e.g. cpu%)

**Comment by bgwalter** [comment]
I think that in terms of the listener, that would make the most sense. As of right now, the only way I can think of to change this is to create a new function that reads the log, takes the difference, feeds it back to the getNetwork function, and then back to the log, which seems awfully roundabout. 

And how would I go about flagging them? Do you mean that something like the CPU be logged with the percent sign in it (7.8%|2.0%|3.6% etc.)?

**Comment by acencini** [comment]
by cumulative, i mean something that increases vs something that is absolute.  it is not tied to units or percentages but more how the data changes.  you could feed rohail a config file that provides the counter names/locations and whether the counter is cumulative or absolute - and heck, you could also provide units etc in there as well so he does not have to generate a million custom graphs.

**Comment by bgwalter** [comment]
@rohailaltaf , I assigned this to you so you can get the difference of the bytes received and sent. Tell me if / how you want units / everything else Andrew is talking about. I'm not sure what the best format for you to get the info you need would be.

**Comment by acencini** [comment]
i am assuming this is fixed?

**Comment by rohailaltaf** [comment]
Havent looked into it yet...too much on my plate. Can anyone else look into it? @vpascow

**Comment by bgwalter** [comment]
I think this issue is basically closed... getting the delta for the network information is now being down on Rohail's end. There are no counters, but I don't think they're needed as (I assume) it works fine now. @rohailaltaf, is there anything you want me to flag or are you good?

**Comment by rohailaltaf** [comment]
If we dont need to show it on the web page we're all good

**Comment by Berrescuda** [comment]
So I guess we're closing this. Good job team.
