### ISSUE TITLE
Open and Close

### ISSUE THREAD

**Issue by ltraynor** [BenningtonCS/GFS#108]
torrent chooses jolteon to resolve this issue

**Comment by acencini** [comment]
i was thinking umbreon would be far more appropriate in this case

**Comment by AlliumApotheosis** [comment]
... Jolteon used thunderbolt

**Comment by AlliumApotheosis** [comment]
Jolteon used thunderbolt

**Comment by AlliumApotheosis** [comment]
Jolteon used secret power

**Comment by AlliumApotheosis** [comment]
Issue is out of usable bugs. 
Defeated Issue Open Close
got 0 pokedollars for winning
awaiting verification

**Comment by AlliumApotheosis** [comment]
verified by @edaniszewski 
Jolteon gained 3445 experience points 
Jolteon gained a level!
