### ISSUE TITLE
protocol messages should be one case

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#11]
this way everybody can normalize to lower case or upper case for comparisons

**Comment by acencini** [comment]
plz work to get protocol baked by m0 (wednesday) - you will need to work with all parties involved to make sure all protocol messages are standardized and clean (and documented)

**Comment by ltraynor** [comment]
the case for everything on the API is uppercase

**Comment by edaniszewski** [comment]
verified for API
