### ISSUE TITLE
clean up the directory in backus and RPIs

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#110]
It looks like there is a lot of extra/unnecessary stuff in the directories that I am not sure is necessary. Go through and remove the things that are not being used by our system..

ps.txt? text.txt? /foxes? the .pyc files?

**Comment by AlliumApotheosis** [comment]
ps.txt is periodically generated by readwhizzifest if deleted it will just come back. the foxes directory and other clutter have been cleaned out. pyc files are cached by python. They are used to speed the startup of the .py file they share a name with. A .pyc file is a previously compiled byte-thing. If you get rid of them python will make more.
