### ISSUE TITLE
pearl.bennington.edu site needs to show the correct chunkservers

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#111]
http://pearl.bennington.edu/

As of right now, the site for the PPE is showing the same chunkservers as used by the PE, (.10, .11, .12, etc). It may just be mislabeling, but it should be corrected to reflect the actual servers being used as chunkservers in the PPE

**Comment by rohailaltaf** [comment]
It reads the ips from /data/gfsbin/hosts.txt and activehosts.txt. Are they correct?

-Rohail Altaf

**Comment by edaniszewski** [comment]
yes, you are right! the hosts/activehosts were incorrect
