### ISSUE TITLE
API - read functionality could return the whole string at once, instead of fragmented reads

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#112]
After testing the read functionality for multi-chunk read, it looks like it reads from each chunk and prints the data separately. I should be possible to make it so the API receives all the data, joins it together, and then prints it as a single string instead of fragmented reads.

**Comment by acencini** [comment]
this sounds like the desired behavior

**Comment by ltraynor** [comment]
I put in the logic, but the PPE is not currently up so I cannot test it

**Comment by AlliumApotheosis** [comment]
Guys, this is running on the PPE, all read outputs are to a file.

**Comment by ltraynor** [comment]
read works gooooooooood.
