### ISSUE TITLE
implement "gmail" over gfs

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#114]
assign to somebody else since this is a big job - just leaving it up to you to decide whom

if you think of each user as a mailbox, and each mailbox as a GFS file, then you have much of what GFS is made up of.

in addition you have a mapping of message metadata to message locations in the file (the metadata may indeed be a separate GFS file).

in addition, you can have a way of sending and receiving mail via SMTP.  this part may be a bigger pain but may be a neat app as well.

**Comment by acencini** [comment]
will this still be happening?  i would prioritize this behind #144 and any live system issues

**Comment by rohailaltaf** [comment]
I can either make a semi impressive youtube+gmail or a really impressive youtube or gmail. I'm already half way through the youtube thing.

**Comment by acencini** [comment]
just do youtube

**Comment by rohailaltaf** [comment]
Closing for now and possibly reopening if there's time before the poster session.
