### ISSUE TITLE
api - command line arguments

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#116]
Is there any way for the API to take command line arguments. I need it to communicate with API.py for the online video share

**Comment by acencini** [comment]
can't you import the API separate from client.py?  that should be easy
enough to do.

that said, having an interactive client using raw_input is not sustainable
long-term and should instead take command line arguments for testing and
primitive automation.

**Comment by rohailaltaf** [comment]
The video share/gmail would be build with PHP/MySQL and I can communicate with the API using the PHP exec() command if it has command-line arguments

**Comment by acencini** [comment]
that will not scale.  exec is expensive, especially if you have to exec for
every function call ( we will learn about fork and exec in OS next term ).

i know all the docs say to use exec/shell_exec but the thing is you're
calling an API and not a program

you might want to consider a different way of integrating with the API -
including possibly not using PHP (sorry)

**Comment by rohailaltaf** [comment]
What if there was another "client.py" which was a TCP server? That way I
could just make POST requests to it and it would respond with the
appropriate data

**Comment by acencini** [comment]
maybe you could use python-flask for that if you could not go beyond php.

**Comment by AlliumApotheosis** [comment]
Done, awaiting verification.

**Comment by rohailaltaf** [comment]
Could you reference the file? I can't see it on git

**Comment by AlliumApotheosis** [comment]
are you looking at the PPE branch? it's client.py
@edaniszewski  verified
