### ISSUE TITLE
Production Environment  Problem. Heartbeat indicates that chunkservers are unresponsive...

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#117]
I ran the end to end test on the production environment after getting it to work locally.
Upon doing so, I got an email listing errors, which lead me to find that all appends were being funneled to the same chunkserver

```
  6
  11988
  plagueplagueplague
  10.10.117.11|10.10.117.11|10.10.117.11|9
```

where the first three lines are a result of the append and the read, and the last line shows that the three locations the append was sent to was the same. as the append message was 'plague', it makes sense that the read message was 'plagueplagueplague' if it were appended to the same place three times. 

I checked the activehosts file, and found that only 10.10.117.11 was active, (even though the website claimed that were active except 10.10.117.11), so I cut the power for a hard restart on all the pis. 

Now, running heartBeat indicates that it can not connect to any of the chunkservers. 

I have `ssh`'d into all of them and `ps -ef | grep chunkserver` to find that they are definitely online, and that they are definitely running the chunkserver script. 

Does anyone have any idea about what may be going on, because I have no idea and haven't been able to fix it.

**Comment by edaniszewski** [comment]
After another try and restart of the system, similar things are happening, except this time, its 10.10.117.10 that is the only active one. 

heartBeat reveals

```
  [Errno 111] Connection refused
```

but I am able to ssh into the chunkservers and manually verify that chunkserver.py is running in the background...

WEIRD!

**Comment by edaniszewski** [comment]
With guidance from @WeedFox , the chunkservers now seem to be responding correctly.

**Comment by acencini** [comment]
what was the issue?

**Comment by edaniszewski** [comment]
There was a bad/stale version of chunkserver.py running in the background on the chunkservers and I was not kicking them properly to refresh them

**Comment by acencini** [comment]
cool

On Mon, Nov 18, 2013 at 8:47 AM, Erick Daniszewski <notifications@github.com
