### ISSUE TITLE
API: User should be prevented from creating or referring to files with the '|' character in the name.

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#127]
As of right now this would cause pretty fatal errors, and could even conceivably be a security loophole(even if that is perhaps a stretch).

**Comment by ltraynor** [comment]
is the case for the command line client program and the raw input client program? either way should be an easy enough fix

**Comment by acencini** [comment]
this should be fixed within the API that is consumed by all programs.
 prior to sending anything out over the wire, the API should check the
filename for junk characters.  alternately, you could rework your entire
protocol to use fixed-sized byte buffers for leading command fields but
that is probably a gigantic item at a late date.

**Comment by acencini** [comment]
what did you decide to do here?  returning error on invalid file names should be ok for this release.

**Comment by ltraynor** [comment]
I just pushed the code that should not allow this anymore. It was only a three line change

**Comment by Berrescuda** [comment]
verified
