### ISSUE TITLE
heartBeat / listener - format to log info to the listener is incorrect

### ISSUE THREAD

**Issue by bgwalter** [BenningtonCS/GFS#128]
@edaniszewski 

line 72 in heartBeat.py:

```
listener.logInfo("FILE READ ERROR", "Could not open or read from hosts file")
```

I did an overhaul to how the listener logs information and now logInfo takes a line number and the information. I'm going to create a new function in the listener that outside programs can use to log errors, so that line will have to change once I figure out how this function is going to work.

**Comment by bgwalter** [comment]
I created another function in the listener called logError. When the listener is imported into another program and it encounters an error that the listener should know about (is there a file that you depend on that isn't there? Tell the listener!), use listener.logError("the error that you want to log"). The code for it looks like so (line 78):

```
def logError(info):
    # If you are using the listener in another program to log an error (such
    # as, if there is a file missing), use this function! If the listener is
    # imported as listener, then this should be used as:
    #         listener.logError("What the error is. Be descriptive!")

    with open(errorLog, 'a') as a:
            a.write(str(info) + '\n')
            logging.debug("Logged " + str(info) + " to the error log.")
```

This is working fine in local tests, both when the listener is running and when it's not. Awaiting verification.

**Comment by edaniszewski** [comment]
confirmed that the new listener logic still works with HeartBeat!
