### ISSUE TITLE
PPE/PE monitoring - have a timestamp show when the last update was

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#135]
I know the PE/PPE sites used to have a timestamp on the bottom of the page to show when the last time the stats were gathered on the system, but I don't see it there anymore.  I think it would be useful to have that back. As of now, the only way to be sure it is working is by inducing a change, and the only change we can make is to have something fail.. making one thing fail to check if another is active seems inefficient.

**Comment by rohailaltaf** [comment]
This is because the pages are checked on demand now. You need to make sure the activehosts.txt and hosts.txt file are always accurate. This is where it picks up the system online status from

**Comment by acencini** [comment]
resolution for this issue?  close?  fix?  knife fight?

**Comment by rohailaltaf** [comment]
Closing
