### ISSUE TITLE
listener - make a log that logs every bit of data rather than in the last hour or so

### ISSUE THREAD

**Issue by bgwalter** [BenningtonCS/GFS#137]
this will log all the CPU, network, memory, and disk space

**Comment by acencini** [comment]
keeping this data around won't hurt and if you are taking 10 measurements every 30 seconds, and each measurement is approx 64 bytes, you have 640 bytes/minute \* 60 minutes \* 24 hours, or 921,600 bytes/day.  the log could be rolled once a week just to keep it below 8MB. (e.g. listener.log becomes listener.log.1, and a new listener.log is started).  this way you keep "soft state" (just like asking the chunkservers what chunks they have) in case there is a centralized loss of listener data.

**Comment by acencini** [comment]
also, it would likely make sense to include timestamps in the listener log for each measurement, to make storing in a database easier and less guessworky

**Comment by acencini** [comment]
and this is acknowledging timestamps between machines may be a little off

**Comment by acencini** [comment]
in our experience, this was ok

**Comment by bgwalter** [comment]
Got it. I'll start working on this tonight.

**Comment by acencini** [comment]
should this be closed??

**Comment by bgwalter** [comment]
Now just needs to be verified

**Comment by Berrescuda** [comment]
Verified
