### ISSUE TITLE
database/master & chunkserver - orphaned chunks

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#141]
In the event that a file is marked for deletion, but a chunkserver that has a chunk of that file on it goes down, the scrubber will get rid of all chunks in the active locations. If/when that chunkserver comes back up, it will then have an orphaned chunk that is not associated with any file. 

How do we want to deal with this?

My thought is to have periodic chunkserver interrogations (finding out the contents of a chunkserver) and checking that across the database. If there is a chunk that is associated with a file that no longer exists, the database should send a command to the chunkserver containing it (I believe this cleaning command already exists in the chunkserver as it is the one it uses with the srcubber), so it can be removed. Does this seem like a good plan of action since without a fileName association, the chunk is essentially useless? @Kgespada @TGlenn

**Comment by acencini** [comment]
could you limit this to happen just when you call "whatchunksyagot" when a chunkserver comes up?

in reality in a real scenario, chunk servers will come and go on a semi-regular basis for automated maintenance (e.g. OS patches, etc.) so doing this super lazily might be ok  :hammer:

**Comment by edaniszewski** [comment]
Yes! My idea was to limit orphan handling in the chunkserver interrogation, where they are asked what they have. 
I brought this up in class and we kind of vaguely said they should just be deleted, but I was hoping to talk to everyone again to be definitively sure that is what we want to do. It should be fairly straightforward to implement. There is already code in place to recognize orphans on interrogate, so it would just be a matter of informing the chunkservers what they need to do.

**Comment by acencini** [comment]
sounds like a plan

**Comment by Berrescuda** [comment]
Verified
