### ISSUE TITLE
way to list all files and chunks in system

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#144]
i forget what happened to this but we used to have a list of all files and all chunks in the system.  it would be helpful to look at the list of files and see their component chunks and the machines they live on.  this is all stuff that we have in the master db so this should be pretty reasonable to dredge out.  i'd like to see it for the demo.

**Comment by rohailaltaf** [comment]
backus.bennington.edu/fileshare/files.php

**Comment by rohailaltaf** [comment]
It just lists file names for now. Is it essential to have chunk handles associated with each file?

**Comment by acencini** [comment]
yes, all chunks and their locations for each file

this was discussed earlier in the project

**Comment by rohailaltaf** [comment]
@edaniszewski is there any way we can enhance the fileList function of the API for this without too much hassle?

**Comment by edaniszewski** [comment]
@rohailaltaf  Yeah, probably. As of now, the only thing that uses it is the API command 'files' which will show what files exist. Since having all the files listed on the site accomplishes essentially the same task, it would make sense to just use whats in place and add whatever is needed for additional info!

**Comment by edaniszewski** [comment]
@rohailaltaf I can write the backend that gets the data from the database, etc, I just need to know what format you want it in. Its pretty straightforward to get a list of files.. [file1, file2, file3], I could get chunks as a 2D list corresponding to the files [[0,1,2], [3,4,5], [6,7]], etc. Or we can come up with something else.. [file1|0:10.10.117.14,10.10.117.11,10.10.117.10|1:10.10.117.13,10.10.117.11,10.10.117.15, .....]

just let me know which would work best for you to parse on the frontend

**Comment by edaniszewski** [comment]
it looks like the files command now returns a string as requested per @rohailaltaf 

```
       |test1*0*10.10.117.101*10.10.117.107*10.10.117.109*|test3*2*10.10.117.109*10.10.117.101*10.10.117.107*|test2*1*10.10.117.109*10.10.117.101*10.10.117.107*
```

so, the format is `|fileName*chunkHandle*location*location*location*chunkHandle*location*location*location*`

etc, for every file. Let me know if this doesn't work for you @rohailaltaf

**Comment by acencini** [comment]
status?

**Comment by acencini** [comment]
verified
