### ISSUE TITLE
http://backus.bennington.edu/fileshare/files.php does not respond

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#148]

**Comment by acencini** [comment]
@edaniszewski @Kgespada

**Comment by rohailaltaf** [comment]
The master is behaving weirdly. Looking into it 

-Rohail Altaf

**Comment by edaniszewski** [comment]
I believe this issue is related to #144 , since that is what this url points to. The monitoring and fileshare upload page seem to be responding. I will close this issue since it should be resolved when #144 is resolved.
