### ISSUE TITLE
combine PPE, production for demo

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#149]

**Comment by acencini** [comment]
@edaniszewski

**Comment by edaniszewski** [comment]
I think this should be done..
all servers except backus, cs, and pearl now have keyless login to backus and have updated quesofiesta/cheespull 

I think all the crontabs are accurate, but I will double check. Pearl needs some additional changes to crontab until it can be merged, I'll work on that next.

**Comment by Berrescuda** [comment]
verified and closed
