### ISSUE TITLE
deploy to 50+ nodes in AWS

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#150]
this can be a scale out environment for testing.

**Comment by acencini** [comment]
@edaniszewski

**Comment by ltraynor** [comment]
50 instances plus a master instance are all running on aws. awaiting for everything to pushed to aws

**Comment by ltraynor** [comment]
the instances now have the cron job on them

**Comment by Berrescuda** [comment]
Right now we're waiting for the rest of the code to catch up to this, but once it does we should be ready to close this easy.

**Comment by Berrescuda** [comment]
... with a loose definition of "easy"

**Comment by ltraynor** [comment]
BY THE POWER OF GRAYSKULL THIS ISSUE HAS BEEN RESOLVED

**Comment by Berrescuda** [comment]
WHAT NOW. WHAT NOW, AWS.

**Comment by edaniszewski** [comment]
Got some tests running on AWS flawlessly!! :metal:
