### ISSUE TITLE
break out hosts file to include function so individual machine types run appropriate functions

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#152]

**Comment by acencini** [comment]
@edaniszewski

**Comment by Berrescuda** [comment]
Consolidated the various branches of our environment into one self contained and easily portable directory. @VulpesArtificem should be able to verify shortly.

**Comment by Berrescuda** [comment]
The new environment has hit an unexpected brick wall, I'll talk to Erick about it tomorrow and we'll get it worked out. We're really close though.

**Comment by Berrescuda** [comment]
So, the original intent of this issue has been dealt with. We're going to close this issue and I'll continue working on Issue #154, which is a more accurate reflection of the work we're doing.

**Comment by edaniszewski** [comment]
verified. A file now exists which conveys machine roles, file structure in backus has been cleaned up and is better/more logical.
