### ISSUE TITLE
backus web page needs to be updated to show correct data

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#155]
Because of the changes in #152, (I think), the backus webpage isn't showing the appropriate data (no indication of any chunkservers or error log data).  I tried updating the host/activehosts/log locations in the index.php file in www/pages, but it didn't  seem to do anything, so I changed it back to the way it was before because I don't want to break anything. 

I'm sure its an easy fix, I'm just not sure what needs to change, but it would be very useful having this up ASAP so we can monitor the system..

**Comment by rohailaltaf** [comment]
Music class from 2-6. After that I'll fix it 

-Rohail Altaf

**Comment by edaniszewski** [comment]
@rohailaltaf is it an easy fix? If it can take you less than 10 minutes, could you try to get it done before then, so we have visibility of the system as we work?

**Comment by Berrescuda** [comment]
works now
