### ISSUE TITLE
backus.bennington.edu most chunkservers do not show the total space/space remaining

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#158]
As of my raising this issue, only one chunkserver is properly displaying its space metric. All the others indicate there there 0 space on it..

**Comment by rohailaltaf** [comment]
Like I said before, any error pertaining to the web stuff can not be fixed until I am able to do this https://github.com/BenningtonCS/GFS/issues/157

**Comment by edaniszewski** [comment]
I know, I know. I just wanted to bring it up so it didn't go unnoticed

**Comment by acencini** [comment]
fixed, verified
