### ISSUE TITLE
calls to recv should make sure they get all the data in master

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#21]

**Comment by rohailaltaf** [comment]
Verified.

**Comment by edaniszewski** [comment]
Found bug in previous implementation where s.recv blocks in the while loop. Re-examining recv logic.

**Comment by edaniszewski** [comment]
@rohailaltaf  please re-review and re-verify

**Comment by rohailaltaf** [comment]
Verified.

**Comment by edaniszewski** [comment]
Torrent brought up that my method will not always work because packet size does not always equal maximum buffer size for sends

**Comment by edaniszewski** [comment]
addressed in Issue #54
