### ISSUE TITLE
in master->api handler->run break ops into functions

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#23]
# If the operation is to CREATE:

```
            if op == "CREATE":
```

... etc

this can get cumbersome in a single function

**Comment by edaniszewski** [comment]
Reassignment of operations to functions leads to out-of-scope issuse. Updating to fix scope

**Comment by edaniszewski** [comment]
@Kgespada  please review and verify

**Comment by Berrescuda** [comment]
Ahem, wrong issue.

**Comment by acencini** [comment]
i think you fixed this , no??

**Comment by edaniszewski** [comment]
Yes, its just waiting to be verified and closed
