### ISSUE TITLE
you can use the mod operator, you know

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#26]
```
            return hostsList[randomInt] + "|" + hostsList[randomInt + 1] + "|" + hostsList[randomInt + 2]
```

if the randomInt is within 3 of the end of the list, why not just use randomInt%len(list)

you can wrap around the end of the list

![the-more-you-know](https://f.cloud.github.com/assets/982017/1394074/912ff618-3c23-11e3-9a8b-503e340ea82c.png)

**Comment by rohailaltaf** [comment]
@edaniszewski plz verify bro

**Comment by edaniszewski** [comment]
reviewed and verified
