### ISSUE TITLE
api - general protocol error handling

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#38]
e.g. what if create does not give you a continue?

**Comment by acencini** [comment]
this should be ongoing until the protocol is baked, but please work on this as part of your work over the next two weeks

**Comment by ltraynor** [comment]
@edaniszewski 
also verify this one, and note that the continues will be removed soon anyway

**Comment by acencini** [comment]
@edaniszewski @ltraynor please make sure there is a suitable level of error handling beyond just the simple example above.  if it is something that can be handled automatically (e.g. via retry), it is worth logging or giving a warning message about; if it is something that cannot be automatically fixed, then we should fail and raise an error.  this is a universal rule, and should apply to all user-initiated cases in the API.

**Comment by ltraynor** [comment]
@WeedFox pls verify

**Comment by AlliumApotheosis** [comment]
I guess... this is verified... 

> .>
> <.<
