### ISSUE TITLE
for api - make this a module and drive it using a separate client (test) program

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#39]
import API

etc

**Comment by acencini** [comment]
you appear to have a test program in place using the API - may make sense to write a test program that consumes all parts of your API to make sure they all work.

**Comment by ltraynor** [comment]
@acencini could you please clarify what you mean, I think my 'client.py' program is what you are asking for but I'm not sure

**Comment by acencini** [comment]
@ltraynor  yes, client.py is a client program, so it would be good to drive the whole api from there as a test however you should come up with a variety of test cases to make sure you put it through its paces

also, client.py should not be interactive - instead, it should take its arguments on the command line.  i think you fixed that already but we shouldn't be using raw_input or anything like that for both production and test code.

**Comment by ltraynor** [comment]
test code has been written, and a few easy alterations allow for command line arguments instead of raw_input
