### ISSUE TITLE
Make a web based GFS statistics page

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#43]

**Comment by rohailaltaf** [comment]
stats.py now generates a file with a list of hosts at http://backus.bennington.edu/stats.html

**Comment by acencini** [comment]
please finalize this and make it professional looking for wednesday.  from there, this bug can be closed and specific additions/fixes can be raised separately.

**Comment by rohailaltaf** [comment]
Need master running to verify this @edaniszewski

**Comment by edaniszewski** [comment]
Debugging now!

**Comment by edaniszewski** [comment]
Verified
 http://backus.bennington.edu/
