### ISSUE TITLE
API function to return a list of all the files on the system

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#44]

**Comment by rohailaltaf** [comment]
Function implemented by me. Waiting for Klemente to change his database structure

**Comment by acencini** [comment]
klemente has updated his database, please check with him and make sure your function does what it should

**Comment by edaniszewski** [comment]
with newest version of the database, it may be useful to consider the lookup dictionary -- this keys all the chunkHandles to the fileName. It is simpler than the data dictionary, as it contains less data, and thus may be easier to parse.

example of what lookup should look like:

`lookup = {"1":"/foo/bar", "2":"/foo/bar", "3":"bar", "5":"foo", "13":"/foo/bar"}`

etc...

**Comment by rohailaltaf** [comment]
Need master running to verify this @edaniszewski

**Comment by Berrescuda** [comment]
Verified
