### ISSUE TITLE
create listener

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#45]
write a listener that acts as a 'big brother' to keep track of the individual components of the GFS implementation -- if something is having a fatal error that automated system management can not handle, have the listener alert someone about it (maybe through email?) so it can then be fixed    

eg. if the hosts.txt file somehow disappears, a new one can not be created automatically.

**Comment by acencini** [comment]
i'm going to put you in charge of automated system monitoring, @vpascow - this task should consist of two pieces:

-write a service that runs periodically and reports (e.g. via email and rohail's web page) critical errors
-add additional capabilities for advanced monitoring (so the service should be fairly modular so additional services can be added)

**Comment by bgwalter** [comment]
I wrote listener.py which should do all that it's supposed to do...

It checks the CPU, memory, disk, and network and puts all of those out to a log file. It also checks to make sure that every file that is supposed to be there is there. All that needs to be done is for the logs to be read, consolidated,  and sent to someone if there is an error.

**Comment by acencini** [comment]
@edaniszewski

**Comment by acencini** [comment]
@rohailaltaf
