### ISSUE TITLE
garbage collection

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#46]
write a scrubbing (garbage collection) protocol that will allow deletion of chunks
### MASTER
- chunks need to have a deletion flag
- delete and undelete commands need to exist
### CHUNKSERVER
- need to be able to receive delete message from scrubber and remove specified chunks
### API
- need to build in commands to allow users to delete (or undelete) files
### SCRUBBER
- should probably run on a chron job
- goes through database to see what is flagged as delete
- tells all chunkservers holding the chunks to delete them
- on confirmation, the opLog and database should be updated to reflect the deletions

**Comment by acencini** [comment]
please make sure the database / master work is in place for this, and coordinate with @ltraynor and @WeedFox to make sure api and chunkserver are ready

**Comment by Berrescuda** [comment]
Master side is done, passing assignment to Torrent @WeedFox who should work with Logan @ltraynor to get this finished up.

**Comment by Berrescuda** [comment]
Did I say Torrent? I meant Brendon

**Comment by ltraynor** [comment]
delete and undelete are operational

**Comment by bgwalter** [comment]
This is implemented and should do what it's supposed to on the chunkservers

**Comment by Berrescuda** [comment]
verified
