### ISSUE TITLE
Implement append across chunks

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#47]
Appending beyond chunksize should create a new chunk and send a message to the Master, which will designate three new chunk locations and pass those back to the api as well as the locations of the previous chunk that needs to be appended to.

**Comment by acencini** [comment]
if this requires work that is not yet queued in other areas of GFS, please relate those bugs here

**Comment by Berrescuda** [comment]
@rohailaltaf @WeedFox @ltraynor 
The protocol for appending across chunks should be as follows:

API tells the master they want to append to a file.
The Master tells the API where the chunk they want to append to is (by sending them the chunkhandle).
The API Tells the relevant chunkservers which chunk to append it's data to, and what that data is.
The chunkservers check to see how much data they can write to that chunk, and if there's overflow they alert the API.
Data should be written to the target chunk until it is full.
In the case of overflow, the API tells the master that a new chunk has to be created, and what chunk it was trying to append to when the chunk got filled.
The master checks to see if this is true (that a new chunk hasn't been created already), and then returns the ips of the new chunk (or whatever the ips of the newest chunk if it's not full) to the API
The API tells the chunkservers where to create new chunks, and attempts to append the remaining data to them. 
Rinse and repeat until all the data is appended.

**Comment by ltraynor** [comment]
so far what I have is the API sends an append request to the master which sends the API the addresses of the chunk that is being appended to. The API then asks the chunk servers how much room is left on this chunk. If there is more data trying to be added then there is room in the chunk, the data trying to be added is split into two parts, the first part being however much data will fit into the current chunk. The API will then tell the master to create new chunks and then run append again with the second half of the first data. When the initial request to append goes to the master, it should return the chunk handle and locations of the new (empty) chunks. If they can fit the remaining data, it works just like a regular append. Theoretically this could be done indefinitely until the remaining data fits into one chunk

**Comment by acencini** [comment]
seems legit

@ltraynor @edaniszewski @Kgespada @rohailaltaf 

when you ask for how much room is left in the chunk, does the master do any accounting for that at that time?  e.g. if you have 600 bytes to append but chunk A only has 200 bytes free, does the master commit those bytes to that append, and then create a new chunk for you to put the remaining 400 bytes in?

another scenario - related - if the protocol is as defined above, what happens:

chunk K has 700 bytes available
client A wants to write 600 bytes
client B wants to write 400 bytes
client A asks how much room is in chunk K
master says "700"
client B asks how much room is in chunk K
master says "700"
client A writes 600 bytes to chunk K
client B attempts to write 400 bytes to chunk K?

this seems awkward but i think you may have the protocol set up right to handle this properly but i am not sure.  this is an example, by the way, of a good test case.

**Comment by acencini** [comment]
if there is any confusion on this, you probably know the desired behavior, so write tests to prove the right thing happens, and if it isn't figure out why it's not happening.

**Comment by ltraynor** [comment]
It has been done

**Comment by rohailaltaf** [comment]
VERIFIED YO
