### ISSUE TITLE
Read: Read until end functionality.

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#51]
Users should be able to read from the current byte offset to the end of the file.

**Comment by ltraynor** [comment]
@WeedFox do you need to change anything so that if the byte offset is -1 it reads until the end? cus if not then we are good to go

**Comment by ltraynor** [comment]
I mean bytes to read not byte offset

**Comment by edaniszewski** [comment]
I think the master should handle the -1 bytes to read and just give you the things you need to send to the chunkservers, but we can double check that logic

**Comment by acencini** [comment]
that seems sound

**Comment by ltraynor** [comment]
verified
