### ISSUE TITLE
Tests for everyone

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#52]
Everyone's code should have tests written for it. Read on unit testing for next week.

**Comment by ltraynor** [comment]
test code for API exists

**Comment by acencini** [comment]
on monday, let's do a quick test review in addition to our progress review.  in particular, each group (cs, master, api) should enumerate the test cases they have and how they are being used.  i imagine the constant end-to-end test in production is moving forward and that is a bit more of a well-defined task.  but let;s check in on this on monday afternoon before we talk autopilot etc.
