### ISSUE TITLE
update all send/recv calls 

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#56]
In response to : #54 

functionLibrary contains a recv function that will receive until there is an end of character at the end of its message. In config.py, there is an eot variable that houses the untypable End Of Transmission character.
- All files that use send() should get config.eot and append it to the end of every message they send
- All files that use recv() should `import functionLibrary` and use functionLibrary.recv() instead

Note that functionLibrary.recv() takes the socket connection as an argument. The current receive size is 1024, but if we want to set that through an argument, it is doable.

**Comment by edaniszewski** [comment]
put the wrong issue # in the commit message, but also updated master send/receive e2a75d24d6eece705c3eab49e8c31b647a3d74c4

**Comment by edaniszewski** [comment]
I believe all instances of recv() and send() in all code has been updated. @Kgespada @WeedFox @ltraynor @vpascow @rohailaltaf  please check your code and verify all instances have been updated.

syntax for `recv`:

import functionLibrary as fL

data = fL.recv(socketConnection)

syntax for `send`:

import functionLibrary as fL

fL.send(socketConnection, message)

The receive function should now look for an end of transmission character
the send function appends the end of transmission character to every message

**Comment by ltraynor** [comment]
verified for the API

**Comment by bgwalter** [comment]
Looks good for the chunkserver
