### ISSUE TITLE
support transmission/storage of binary data

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#57]
this may throw a wrench into the current send/recv pieces

if i want to open up a file (say, a 8gb video file or something) and store it in gfs, i'd use the API to append this to a GFS file

however, the data in a video may be any old set of bytes

so it may be necessary to add some more robustness to the protocol - e.g. passing in additional info on transmission (data length, etc.) as the first few bytes so the receiver knows how much to read and store, etc.  this is a common tactic in most binary protocols - oftentimes, the first N bytes (e.g. first 4 bytes) are the unsigned length of the rest of the payload.  real heroes also include a checksum at the beginning of the packet, but that is not necessary here.

**Comment by acencini** [comment]
also: related to #56

**Comment by edaniszewski** [comment]
In thinking about how to refactor this, I was thinking if it would make sense for different types of data to be sent and received ( strings, binaries, etc) or would it make more sense for all data to be stored as binary, and the API just converts it eg from string --> binary on send to chunkservers or from binary --> string on read?

This is more of an open question for discussion, as I didn't see much about what things were stored as in the GFS paper, other than "a plain Linux file on a chunkserver"

**Comment by acencini** [comment]
text files and binary files are the same under the covers - it's more of how you work for them (e.g. readline works for a text file but not a binary file).  if you think of all files as binary files, and then think of how you can make working with text a little easier, then you might be well-served.

**Comment by AlliumApotheosis** [comment]
wait.... readline DOESN'T work!? I'm confused then, because i was looking around to get an idea of what i was doing and i did a readline of sublime text and it worked.... kind of...?

**Comment by acencini** [comment]
of the binary?  treating a binary file like a text file will produce unspecified results.  readline simply looks for the newline character in a stream of bytes; it may very well be the case that a byte or sequence of bytes in sublimetext happened to look like a newline character, causing the readline to "succeed".  in reality readline is only meaningful for text files, where newline characters will only be present to signal the presence of a newline.

**Comment by AlliumApotheosis** [comment]
ah. well in other news, all data now storeable as binary data, and retrievable, however i can't seem to do it with an initially binary thing quite yet.

**Comment by acencini** [comment]
how did this turn out today?

**Comment by AlliumApotheosis** [comment]
How did this turn out? hmm... I dunno. 
![foxtest 1000 1001 1002](https://f.cloud.github.com/assets/5447423/1570621/04ada4fa-50f1-11e3-9c6a-1b0948642ea2.jpg)

Why don't you try asking this fox who was thrown into the GFS and subsequently retrieved? 
What's that? his vocal chord bytes are all in the same place they were before? 
well how about that.

awaiting verification

**Comment by AlliumApotheosis** [comment]
Update. It also successfully stores and retrieves sublime text. Verified @Kgespada.com

**Comment by acencini** [comment]
grumpy cat photo or it never happened
