### ISSUE TITLE
database - on DELETE, mark chunk flags to True

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#59]
When the master receives a command to delete, it will alert the database with a delete message "DELETE|fileName" . The database should then change the `self.delete` flag to `True` for all chunks associated with that file (file->chunk lookup should be easy with #58) 

when all the flags are marked, a success ack should be sent back. If something goes wrong (maybe the given file does not exist in the db?), send back a failure ( -1 seems to be what we are using for failures, so that would work)

**Comment by edaniszewski** [comment]
related to #27

**Comment by Berrescuda** [comment]
Verified
