### ISSUE TITLE
database - on UNDELETE, mark chunk flags to False

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#60]
In the off chance that someone deleted a file, but realized they didn't want it deleted, they have a window of opportunity to recover it because it will not delete until the scrubber runs, it will just be marked for deletion until then. 

when the database gets an UNDELETE message, "UNDELETE|fileName" , it should undo the DELETE, that is, for all chunks associated with the given file, set the `self.delete` flag to `False`

similar to the delete, acks should be sent back to the master - on success, and on failure (file may not exist if it has already been deleted)

related: #27 

Issues that may need to be addressed down the line:
-What happens if, as the scrubber is deleting the files off the chunkservers, someone issues an undelete request?

**Comment by Berrescuda** [comment]
Verified
