### ISSUE TITLE
database - permanent delete update from scrubber.py

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#61]
When the scrubber runs, it will ask the database for all files/chunks marked for deletion. It will need to know: the chunkHandle of the chunk, and the locations of the chunk. 

Once the scrubber knows which chunks are to be deleted, it will ask the chunkservers containing that chunk to delete it. Once all chunks have been deleted from the chunkservers, the scrubber will send the database the list of chunks (or fileNames, whichever is easiest) that have been removed from the chunkservers so they can be removed from the database.

**Comment by Berrescuda** [comment]
Apparently Erick already wrote this. Assigning it to him.

**Comment by edaniszewski** [comment]
also, commit d895c08737deaccefa83406c282eca919016faa9

based on database unit tests, this looks like it should be good to close @Kgespada

**Comment by Berrescuda** [comment]
Verified
