### ISSUE TITLE
chunkserver - functionality to delete chunks

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#62]
Periodically, scrubber.py will run and find which files/chunks have been marked for deletion from the database. 

When it knows what is to be deleted, it will send delete requests to the chunkservers holding those specific chunks ( we need to establish what the message protocol is ) The chunk server should be able to parse the delete request, find and remove the specified chunk, and return an ack of success or failure.

related: #27

**Comment by Berrescuda** [comment]
Work with @edaniszewski on this.

**Comment by bgwalter** [comment]
Implemented and waiting to be verified

**Comment by bgwalter** [comment]
Verified by Torrent
