### ISSUE TITLE
please add some more comments!

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#63]
In the API, specifically the threaded objects chunkConnectCreate, chunkConnectRead, chunkConnectAppend, there are very few comments, and I was having trouble following what some of what was going on, specifically the multiple instances of `if dat == "continue":`
could you please clarify whats going on there?

As an additional note, I noticed that, for example:
`if dat == "continue":
            fL.send(self.s, self.cH)
            print self.cH`

what happens if it doesn't receive a "continue"? theres nothing to catch the case where that may happen, if it could

**Comment by ltraynor** [comment]
@edaniszewski 
please verify as well

**Comment by edaniszewski** [comment]
looks good!

verified
