### ISSUE TITLE
All programs should the logging to a .log file instead of a .txt file

### ISSUE THREAD

**Issue by bgwalter** [BenningtonCS/GFS#64]
@Kgespada @WeedFox @edaniszewski @ltraynor @rohailaltaf : there should be a line in most of this programs that have logging capabilities that will be something along the lines of 

logging.basicConfig(filename='chunkserverLog.txt', format='%(asctime)s %(levelname)s : %(message)s')

Please change the file extension in the filename from .txt to .log

**Comment by rohailaltaf** [comment]
Verified.
