### ISSUE TITLE
design and implement physical enclosure for pi nodes

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#65]
logan, i'd like you to take on the task of helping manage the design and implementation of the physical enclosure for the raspberry pi nodes that make up our gfs cluster.

we'd like to have the nodes in their enclosure by beta.  this would include:

-a structure to hold the boards and drives securely
-cable management (power, ethernet, USB/SATA)
-labeling/signage

thanks

**Comment by acencini** [comment]
the nodes are getting cold!  winter is almost here!

**Comment by ltraynor** [comment]
Im working on it!

**Comment by acencini** [comment]
i have moved this to release.  i should not stick this just on you.  we'll figure it out together.

**Comment by ltraynor** [comment]
well in that case I virtually did nothing in beta

**Comment by acencini** [comment]
@BenningtonCS/estudiantes - hey gang, let's get something in place for wednesday so we can get the apparatus set up to roll out into the hallway for a dry run.

**Comment by Berrescuda** [comment]
Upon closer inspection, it seems more and more unlikely that the enclosure is going to get produced tomorrow. Maybe we could spend some time working on it on Wednesday and perhaps do a dry run on Thursday if possible? Just a thought about prioritizing stuff.

**Comment by acencini** [comment]
we have a solution

**Comment by acencini** [comment]
this is dependent on my not cutting all my fingers off with my table saw tonight

**Comment by ltraynor** [comment]
enclosures made.
