### ISSUE TITLE
Update runner to handle versions and run/kick appropriately.

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#66]
Go team.

**Comment by acencini** [comment]
please review your strategy for this with me before implementing.  email is fine if you can't find me.

**Comment by acencini** [comment]
@WeedFox @Kgespada what's up with this?

**Comment by AlliumApotheosis** [comment]
It's awaiting verification, but it has passed testing

**Comment by AlliumApotheosis** [comment]
VERIFIED BY LO-GAN
