### ISSUE TITLE
API and Chunkservers must exchange acknowledgments at chunk creation.

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#67]
@WeedFox and @ltraynor should implement a protocol for acknowledgments between the API and chunkserver for successful and failed chunk creation.

**Comment by acencini** [comment]
acks are useful for debugging via wireshark.  errors are useful for retry/surfacing errors to the client.  think about how you want to be able to trace protocol messages through the system, and how you'd do debugging.  for failed chunk creation that is a definite must that the chunkservers let the master / api know that they're unable to create a chunk!

**Comment by acencini** [comment]
@WeedFox update your bugs - what is going on with this?

**Comment by AlliumApotheosis** [comment]
waiting on verification

**Comment by AlliumApotheosis** [comment]
Logan/Vpascow joint verification
