### ISSUE TITLE
More info on GFS master web page

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#68]
Ability to get chunkserver logs, space, and other controls

**Comment by acencini** [comment]
if you look at nagios, they have some neat monitoring stuff.  but we cannot use nagios in our case, so we would want to (a) present data nicely and (b) be able to gather it somehow.

CPU, disk, memory, at system and process level would be neat, graphable over time.

in bing we had a way of doing this by polling the internal system performance counters (we took a list of counter names as a config file), and for every polling interval put the data into a log such:

<timestamp>|<countername>|<countervalue>

now, sampling counter values, getting mins/maxes over an interval, etc. become tricky.  but getting absolute values is easier.

the above log then gets collected or shipped off to somewhere else, where it is aggregated and presented either on a per node basis or as an overall indicator for the system.

**Comment by rohailaltaf** [comment]
Shows space remaining and links to chunkserver logs. Need master running to veriy @edaniszewski

**Comment by Berrescuda** [comment]
verified - with the note that this will be worked further on as the project develops.
