### ISSUE TITLE
master/database - in createNewChunk, error -3 could be handled automatically

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#71]
If a new chunk has been created already, instead of alerting anyone, just select that new chunk to append to.. I think this could work, so it would be one less error we would have to alert anyone about..

of course, this will be hairy until OPEN and CLOSE are implemented because it may be that multiple people could append at the same time? But that is an issue for later!

**Comment by acencini** [comment]
transparency would be good from user's side - so i think your intuition is right here.  just make sure you can trace this thru logs and protocol for later when you get into crazytown.

**Comment by Berrescuda** [comment]
Hey guys, this issue is dependent on the protocol that y'all will develop for multi-chunk append. In the case of error three, the master should redirect the API to the latest chunk and tell them to append to it.

**Comment by edaniszewski** [comment]
will need to work with @ltraynor  to make sure the API can now handle the change in errno -3

**Comment by Berrescuda** [comment]
11f0ae9c065caf27434e268fd5dcc0806767b701
done

**Comment by Berrescuda** [comment]
waiting for @edaniszewski to verify

**Comment by edaniszewski** [comment]
verified
