### ISSUE TITLE
functionLibrary - improve send/recv acks

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#72]
Currently, the ack protocol is to just send back whatever message was received.. This is probably okay for the simple CREATE, APPEND, CONTINUE, etc, messages, but when large amounts of data will be sent, this would more than likely take a toll on network load/system efficiency. It may be worthwhile to come up with a simple ack... RCVD.. OK.. K... just something short and sweet so it does not add much load to the system.

**Comment by acencini** [comment]
agreed most system level protocols (e.g. NOT http) use numeric/binary codes as part of protocol

i would also urge people to read the paper carefully wrt acks to make sure we are not going too deep on acks other than for debugging purposes.

**Comment by edaniszewski** [comment]
@Kgespada  

Based on the GFS paper's lack of acks, and the fact that TCP kind of already has them built in, I think we should remove the acks in the send/recv functions. We should work on this soon since its been an open issue for a while, and it will greatly reduce the network load, especially with our end-to-end tests coming up..

**Comment by Berrescuda** [comment]
aa106d4c218336510cda34ebde5ed02d7df9fbfa
done, @edaniszewski verify and close?

**Comment by edaniszewski** [comment]
09423b7d1992e6abd131d1f93279a02d204d2294

you linked to the wrong commit, but it looks good! retested send/recv and the acks do not appear anymore. verified.
