### ISSUE TITLE
unused pi

### ISSUE THREAD

**Issue by rohailaltaf** [BenningtonCS/GFS#75]

**Comment by acencini** [comment]
plz make sure there are no dependencies on the existing setup.  also, it might be good to round out the tests by adding one or two other servers from the server room to the rotation.  let me know which ones we need a login for and i can get that set up.

**Comment by rohailaltaf** [comment]
waiting for another drive

**Comment by acencini** [comment]
come to think of it how much room is on the geocities drive?  if it is more than like 50GB then just use that for now and we will swap in a good one later.

**Comment by acencini** [comment]
@rohailaltaf

**Comment by rohailaltaf** [comment]
New pi up and running

**Comment by edaniszewski** [comment]
@rohailaltaf make sure you update hosts.txt to add it to the system

**Comment by rohailaltaf** [comment]
Already done
