### ISSUE TITLE
handle chunkserver failure/departure

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#76]
if i pull the plug on rpiXXX what happens?  we need to detect failure and recover - if a chunkserver goes away, what does THE PAPER SAY about what to do?

this includes partial failures (e.g. chunkserver is running but unable to locate any of its chunks)

does the API inform the master of missing chunks?  consult THE PAPER (magic:8ball:)

**Comment by Berrescuda** [comment]
@edaniszewski

**Comment by acencini** [comment]
please raise the priority on this one now that you have end-to-end largely working.  this will be a finnicky beast and will take considerable time and experimentation to get "right" in a way that is transparent to user.  remember:  transparency is one of the fundamental principles of distributed systems - in that the user should use the API and not have to consider the fact that the system is made up of a system of systems.

**Comment by edaniszewski** [comment]
Yes, @Kgespada and I have spent some time discussing this yesterday and developing a design which would allow for total transparency. Implementation of this should begin tonight/tomorrow.

**Comment by edaniszewski** [comment]
Majority of this has been completed. Build still unstable, so no commit. Further testing and bug fixing tomorrow with @Kgespada should resolve outstanding bugs related to chunkserver arrival/departure

**Comment by acencini** [comment]
this is exciting - this is a critical feature and we should test the hell out of it

**Comment by edaniszewski** [comment]
Tests show that it works with both single chunks and multiple chunks. Its difficult to test the dynamics across a large amount of chunkservers, but in my local testing with 4 chunkservers running ( via ssh), it seemed to operate smoothly! Definitely more testing is needed, but the good news is that it seems fairly stable and very few bugs were encountered throughout the testing.

**Comment by acencini** [comment]
a test scenario for this would be to play 'youtube' video uninterrupted for this.  for example, start playing a video from gfs, then unplug one or two pis and have it continue uninterrupted, repeatably over and over as different pis join and depart.

you could get a video of http://benningtonfreepress.org/archives/2013/11/19/21-questions-an-interview-with-ivan-ooze and have it be their exclusive debut for the poster session

**Comment by bgwalter** [comment]
@edaniszewski demonstrated this to me. Verified!

**Comment by acencini** [comment]
it is always possible to add AWS nodes or test in a giant setting in AWS
with like 400 nodes.  you guys will be getting back into AWS in class
tomorrow but might not be the worst demo case as well.  400 nodes is pretty
spectacular.

On Tue, Nov 19, 2013 at 9:50 PM, Erick Daniszewski <notifications@github.com
