### ISSUE TITLE
Master -- Chunkserver Location Selector should have a case for handling less than 3 active chunkservers.

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#81]

**Comment by Berrescuda** [comment]
On startup, if less than three chunkservers exist, throw an error to the API.

**Comment by edaniszewski** [comment]
In reference to the above comment, database should now inform on startup and log when less than 3 chunkservers are active.

**Comment by Berrescuda** [comment]
Added some handling for insufficient number of hosts in chooseHosts()
a7a2ecb6e806aa025c0a1f5f9bdedd995dcb81fb
waiting on @edaniszewski for verification

**Comment by edaniszewski** [comment]
verified, with the note that we will want to expand upon this in the future, especially once we have load balancing in place.
