### ISSUE TITLE
API/database duplicate CREATECHUNK call.. decide where it will be called and fix.

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#83]
line 314 in database:

```
         fL.appendToOpLog("CREATECHUNK|" + str(chunkHandle) + "|" + fileName)
```

lines 122 - 130 in API:

```
         try:
                    opLog = updateOpLog("OPLOG|CREATE|"+cH+"|"+filename)
                    opLog.start()
            except:
                    print "COULD NOT UPDATE OPLOG"

            opLog = updateOpLog("OPLOG|CREATECHUNK|"+cH+"|"+filename)
            opLog.start()
```

These conflict and add duplicate CREATECHUNK messages to the opLog.. not good! Also, within the try block, it sends a CREATE message, which is no longer parsed by database init, so its kind of useless..

We need to decide where the opLog update will occur......

**Comment by Berrescuda** [comment]
I'll delete the one in the API, as it seems extraneous and more complicated. I'll look at it a bit more beforehand before I do though.

**Comment by edaniszewski** [comment]
b175394c05dd6e2e496b1178aa258c139805a877

**Comment by ltraynor** [comment]
verified.
