### ISSUE TITLE
chunkserver, line 117 - on append, OSError is thrown -> unable to find the specified chunk

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#84]
line 117: 

```
            emptySpace = mg64 - os.stat(chunkHandle).st_size 
```

returns the error

```
    OSError: [Errno 2] No such file or directory: '6'
```

make sure this line works, write a test to make sure it does.. and fix it! It appears that it is unable to find the specified chunk, but a quick look into the Chunks folder shows that it does indeed exist.

**Comment by rohailaltaf** [comment]
is this because the CREATECHUNK (createChunk() in master) not append to the oplog after it creates it? @edaniszewski

**Comment by edaniszewski** [comment]
No, this is a problem within the chunkserver as far as I can tell. 

creating and reading from a file seem to be working currently, but when an append command is given (so far tested to be a non-overflow append), the debug trace shows that the master gets and sends the proper data to the API and that the API receives that data. It also appears that the API is able to parse the data correctly, and that its an inability within the chunkservers to locate the specified chunk. I looked into the Chunks folder, and the chunk was there, so its not a matter of looking for a non-existent chunk. Considering it is an OSError, Im guessing the likely culprit is the `os.stat(chunkHandle).st_size` from the code in line 117 above.

**Comment by edaniszewski** [comment]
this may be as simple as changing `os.stat(chunkHandle).st_size` to `os.stat(config.chunkPath+"/"+chunkHandle).st_size`

Not sure though.. I'm somewhat unfamiliar with os.stat

**Comment by AlliumApotheosis** [comment]
... I'll look into it, but it looks like it just needs to have the chunk path so that it knows where to look for the "6"...?

**Comment by edaniszewski** [comment]
From my tests, there are no errors thrown on the master/db, API, or chunkserver now, but no data is appended to the chunk. Also, it appears that when the API issues a command, it only does so to one chunkserver.

There is probably faulty logic in either the API append function or the chunkserver append function, both should be reviewed. @ltraynor @WeedFox @vpascow

**Comment by acencini** [comment]
command sent to just one chunkserver seems like a good candidate for a new
issue for tracking.  that is a critical error.

append not working is also a separate issue to be investigated on a
critical basis.  we cannot go into beta if the system cannot even accept
data.

On Wed, Nov 13, 2013 at 9:55 AM, Erick Daniszewski <notifications@github.com

**Comment by acencini** [comment]
that said, if the original issue in this bug is fixed it can be closed in place of the two issues above

**Comment by edaniszewski** [comment]
original issue appears to be fixed in my end-to-end test. Closing. new issues created.
