### ISSUE TITLE
API -- READ functionality, bug with sending messages to chunkservers

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#85]
In the API, read (lines 216 - 277), it looks like there is some bad definitions.. ie, theres `self.offSet` when it should just be `offSet`. Go through and make sure all the variable definitions are correct!

**Comment by ltraynor** [comment]
@edaniszewski 
please verify

**Comment by edaniszewski** [comment]
3bed74c7a8cc01678bf8bf84b33e04de7701aac6

seems like everything has been caught and runs now.

verified.
