### ISSUE TITLE
listener --- line 145-151 may need to include T/F check in for loop?

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#87]
It is late, so my logic may be off, but because the for loop is potentially going through multiple items, I think the check for whether the item is in the directory or not should happen for each item...

```
    # check to see if there is an item in files that is not in current
    for item in files:
            isThere = item not in currentFiles

    # if a file is missing
    if isThere == True:
            # log a critical error. This needs to be checked!!
            logging.critical("File missing from directory!!")
```

so, I think `isThere` will just hold the T/F value for the last item in files, so checking if it == True outside the loop really only checks the validity of the last item..

Again this could be incorrect, but think it over! If it is wrong, you have permission to make fun of me for it for years to come.

**Comment by bgwalter** [comment]
You're totally right. I guess I didn't fully test that... I'll check it over.

**Comment by bgwalter** [comment]
I think I fixed it. Now, instead of 'for item in files ...' it is  
 if all(item in currentFiles for item in files): isThere = False
        else: isThere = True

This seems to work fine in my testing. Does it look good on your end?

**Comment by edaniszewski** [comment]
that seems like it works! verified
