### ISSUE TITLE
API/chunkserver -- on append, it appears that only one chunkserver gets a command

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#89]
in an end-to-end test, on an append call, it appears that the API only send commands to one chunkserver, instead of all the chunkservers associated with a chunk. This is a big problem.

**Comment by edaniszewski** [comment]
related #84

**Comment by ltraynor** [comment]
all three pi's are contacted with regular append. still working on append across chunks

**Comment by ltraynor** [comment]
someone verify!
