### ISSUE TITLE
chunkserver -- Append command does not result in data appended to the chunk

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/GFS#90]
in an end-to-end test, append did not append any data to the chunk.

**Comment by edaniszewski** [comment]
related #84

**Comment by AlliumApotheosis** [comment]
in a chunkserver test it does append

**Comment by edaniszewski** [comment]
okay! I'll reassign this to @ltraynor then. It may be some kind of problem with the messages being sent between the two of you? talk to him and make sure everything is all good..

**Comment by ltraynor** [comment]
someone verify!

**Comment by ltraynor** [comment]
append is working
