### ISSUE TITLE
chunkserver: on read, append, sanitize, getsize need to handle io errors

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#92]
you handle IO errors well on create; you do not handle IO errors on these other things which could be a problem

for example, if you are unable to read a chunk due to IO error, or append to chunk due to IO error, you log the error but never let the API know.

by the way, keeping a running count of these errors that can be reported via the listener  @vpascow wrote would be good.  that way we can remotely monitor this and if a chunkserver is giving a lot of random errors, we can investigate further.

**Comment by AlliumApotheosis** [comment]
Handled, verified by the illustrious acencini
