### ISSUE TITLE
Format listener log

### ISSUE THREAD

**Issue by bgwalter** [BenningtonCS/GFS#93]
Line 1 will be the CPU, each item separated by a pipe.
Line 2 will be the Memory
Line 3 the network
and 4 and the disk

Once each line has 60 items in it, the first item will be deleted so that there are never more than 60 items in a line.

**Comment by bgwalter** [comment]
I created listener2.py that has some functionality to make this correctly logable. Right now, all that works is the CPU, and it does not yet work if the listenerLog.log is an empty file.

**Comment by bgwalter** [comment]
@rohailaltaf , look at listener2.py - this should log all the information that you need. Tell me if there's anyway you want it changed.

**Comment by rohailaltaf** [comment]
verified
