### ISSUE TITLE
debug error handling in various components appears redundant

### ISSUE THREAD

**Issue by acencini** [BenningtonCS/GFS#95]
several files, including master.py, api.py, chunkserver.py have this repeated block of code (some of the log files vary).  could you refactor the code to clean this up so this moves to a function from your common library that just takes the appropriate input to configure the logging?  fix your area and pass it along
###### 
# Verbose (Debug) Handling
###### 
# Setup for having a verbose mode for debugging:
# USAGE: When running program, $python chunkserver.py , no debug message will
# show up. Instead, the program should be run in verbose, $python chunkserver.py -v ,
# for debug messages to show up
# Get a list of command line arguments

args = sys.argv
# Check to see if the verbose flag was one of the command line arguments

if "-v" in args:
        # If it was one of the arguments, set the logging level to debug 
        logging.basicConfig(level=logging.DEBUG, format='%(levelname)s : %(message)s')
else:
        # If it was not, set the logging level to default (only shows messages 
        # with level warning or higher)
        logging.basicConfig(level=logging.INFO, filename='httpServerFiles/chunkserverLog.log', format='%(asctime)s %(levelname)s : %(message)s')

**Comment by Berrescuda** [comment]
ba970940d20ea6ac78421d721c7e1c39eb949234
aa106d4c218336510cda34ebde5ed02d7df9fbfa
(sorry about the double commit, I forgot to add a couple files.)

Should be all handled now, no need to pass it around.

@edaniszewski if you could verify and close this that'd be great.

**Comment by edaniszewski** [comment]
I'm not sure your fix will work quite right. In the fL debug, I see that the default (non verbose) debug will add all error messages, etc, to a file called apiLog.log

That would be good for the API, but for the master, it should log to masterLog.log

Overall, the changes look okay, but I'm not going to close this just yet, until we at least add a parameter to decide where to log to.

**Comment by edaniszewski** [comment]
Also, we seem to be getting an error when this is run because lister imports functionLibrary and functionLibrary imports listener..

**Comment by edaniszewski** [comment]
I've been trying to remedy this, and it seems that removing logging setup from the head of files results in an inability to use logging well. Having the logging setup centralized does not allow:
- log files to be created, even when they are specified as a parameter
- -v to enable verbose mode. Now debugging messages will not show up with the -v flag is given.

I'm looking more into the logger module to see if there is a way to fix this.

**Comment by edaniszewski** [comment]
it looks like the problem I ran into in my previous comment was a result of my test setup in someway. After coming back to it, @Kgespada 's fix mostly worked. I still had trouble with passing in a logfile as a parameter, so I made a debug function for the master components and a different one for the chunkserver comonents. I also removed import listener from functionLibrary so it would be able to run. 

Klemente, please check to make sure the changes I made work with yours, then you can close the issue if it does work

**Comment by Berrescuda** [comment]
verified
