### ISSUE TITLE
API- client crashes when anything but 'no' entered after command

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#96]
client.py asks user if they would like to enter another command, and then crashes if they don't say no. Fix this.

**Comment by ltraynor** [comment]
@Kgespada I am well aware of this and have been trying to fix it for a while. its trickier than you think. Also Id hardly call this critical since you can just say no and then rerun the program....

**Comment by acencini** [comment]
this issue has a lot of flair

**Comment by ltraynor** [comment]
This works. someone verify

**Comment by edaniszewski** [comment]
looks good! verified
