### ISSUE TITLE
multichunk read behaving strangely

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#97]
Reading across chunks doesn't seem to be choosing chunkservers appropriately. This should be looked into.

**Comment by edaniszewski** [comment]
@Kgespada I either haven't been able to replicate this, or I don't know what I am looking for.. are there any more specifics on what exactly the strange behavior was? I think you mentioned that it seemed to read from seemingly random chunks? Is there a log of this happening, or can someone show me the debug messages for this occurring?

**Comment by Berrescuda** [comment]
Yeah, I think this issue is probably a bit premature, closing.
